# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: worker.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 31, 1, "", "worker.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x0cworker.proto\x12\x11mastermind.worker"t\n\x15ProcessWebhookRequest\x12\x10\n\x08trace_id\x18\x01 \x01(\t\x12\x0f\n\x07\x63hannel\x18\x02 \x01(\t\x12\x0f\n\x07payload\x18\x03 \x01(\t\x12\x11\n\tsender_id\x18\x04 \x01(\t\x12\x14\n\x0cmessage_type\x18\x05 \x01(\t"\x90\x01\n\x16ProcessWebhookResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x15\n\rerror_message\x18\x02 \x01(\t\x12\x13\n\x0b\x61i_response\x18\x03 \x01(\t\x12\x19\n\x11suggested_channel\x18\x04 \x01(\t\x12\x1e\n\x16processing_duration_ms\x18\x05 \x01(\x03\x32o\n\x06Worker\x12\x65\n\x0eProcessWebhook\x12(.mastermind.worker.ProcessWebhookRequest\x1a).mastermind.worker.ProcessWebhookResponseb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "worker_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_PROCESSWEBHOOKREQUEST"]._serialized_start = 35
    _globals["_PROCESSWEBHOOKREQUEST"]._serialized_end = 151
    _globals["_PROCESSWEBHOOKRESPONSE"]._serialized_start = 154
    _globals["_PROCESSWEBHOOKRESPONSE"]._serialized_end = 298
    _globals["_WORKER"]._serialized_start = 300
    _globals["_WORKER"]._serialized_end = 411
# @@protoc_insertion_point(module_scope)
