import { writeFile } from 'fs/promises'
import { join } from 'path'

const OUTPUT_FILE = join(process.cwd(), 'src/types/api.ts')

const CONTENT = `// Auto-generated by generate-types.ts — DO NOT EDIT
import { z } from 'zod'

// Matches mastermind_cli/types/auth.py LoginRequest
export const LoginRequestSchema = z.object({
  username: z.string().min(1).max(100),
  password: z.string().min(1).max(100),
})

// Matches mastermind_cli/types/auth.py TokenResponse
export const TokenResponseSchema = z.object({
  access_token: z.string(),
  refresh_token: z.string(),
  token_type: z.string().default('Bearer'),
  expires_in: z.number().default(1800),
})

// Matches WS brain event data shape (inspect coordinator in Task 2)
export const BrainEventSchema = z.object({
  brain_id: z.string(),
  status: z.enum(['idle', 'active', 'complete', 'error']),
  timestamp: z.number(),
})

// WS message envelope (task_update_batch)
export const WSMessageSchema = z.object({
  type: z.literal('task_update_batch'),
  data: z.array(BrainEventSchema),
})

export type LoginRequest = z.infer<typeof LoginRequestSchema>
export type TokenResponse = z.infer<typeof TokenResponseSchema>
export type BrainEvent = z.infer<typeof BrainEventSchema>
export type WSMessage = z.infer<typeof WSMessageSchema>
`

async function generateTypes() {
  await writeFile(OUTPUT_FILE, CONTENT, 'utf-8')
  console.log(`✅ Generated ${OUTPUT_FILE}`)
}

generateTypes().catch(console.error)
