"""
MM-Flow Checkpoint Writer

Detects write tool calls in recent transcript messages and writes
SESSION-CHECKPOINT.md when changes are detected.

This file is in the repository (NOT ~/.mm-flow/) for:
1. Version control — checkpoint logic evolves with the project
2. CI testability — no Claude Code runtime required
3. Distribution — available on every checkout
"""

import json
import sys
from datetime import datetime
from pathlib import Path
from typing import Any

WRITE_TOOL_NAMES = frozenset({"Edit", "Write", "MultiEdit"})
BASH_MUTATION_PATTERNS = [
    " > ",
    " >> ",
    "tee ",
    "touch ",
    "mkdir ",
    "mv ",
    "cp ",
    "rm ",
]
CHECKPOINT_PATH = Path(".planning/SESSION-CHECKPOINT.md")


def has_write_operations(transcript: list[dict[str, Any]], window: int = 10) -> bool:
    """
    Return True if any of the last `window` messages contain write tool calls.

    Write = Edit/Write/MultiEdit tool, or Bash with mutation patterns.
    Read-only sessions (grep, cat, ls, read) return False.

    Args:
        transcript: List of message dicts from the Claude Code session.
        window: Number of recent messages to inspect (default 10).

    Returns:
        True if write operations were detected, False otherwise.
    """
    recent = transcript[-window:] if len(transcript) >= window else transcript
    for message in recent:
        tool_calls = message.get("tool_calls") or message.get("tool_use", [])
        if isinstance(tool_calls, list):
            for tc in tool_calls:
                name = tc.get("name", "") if isinstance(tc, dict) else ""
                if name in WRITE_TOOL_NAMES:
                    return True
                if name == "Bash":
                    cmd = ""
                    if isinstance(tc, dict):
                        inp = tc.get("input", {})
                        cmd = inp.get("command", "") if isinstance(inp, dict) else ""
                    if any(p in cmd for p in BASH_MUTATION_PATTERNS):
                        return True
    return False


def write_checkpoint(
    transcript: list[dict[str, Any]],
    checkpoint_path: Path = CHECKPOINT_PATH,
    timestamp: str | None = None,
) -> Path:
    """Write SESSION-CHECKPOINT.md with saved=false.

    Args:
        transcript: Full session transcript for context extraction.
        checkpoint_path: Target path for the checkpoint file.
        timestamp: ISO timestamp override (default: now).

    Returns:
        Path where the checkpoint was written.
    """
    ts = timestamp or datetime.now().isoformat()
    # Extract last few assistant messages as context
    summaries = []
    for msg in reversed(transcript[-20:]):
        if msg.get("role") == "assistant":
            content = msg.get("content", "")
            if isinstance(content, str) and len(content) > 20:
                summaries.append(content[:200])
                if len(summaries) >= 3:
                    break

    checkpoint_path.parent.mkdir(parents=True, exist_ok=True)
    checkpoint_path.write_text(
        "---\n"
        "saved: false\n"
        f"last_updated: {ts}\n"
        "---\n\n"
        "# Session Checkpoint\n\n"
        "Auto-generated by mm-flow-stop hook.\n"
        "Write operations detected in last 10 messages.\n\n"
        "## Recent Activity\n\n" + "\n\n".join(f"> {s}" for s in summaries) + "\n\n"
        "## Action Required\n\n"
        "Call `mem_session_summary` at start of next session to preserve this work.\n"
    )
    return checkpoint_path


def main() -> None:
    """Entry point called by mm-flow-stop.js via stdin JSON."""
    try:
        data = json.load(sys.stdin)
    except (json.JSONDecodeError, EOFError):
        sys.exit(0)  # No data, skip silently

    transcript = data.get("transcript", [])
    if not transcript:
        sys.exit(0)

    if has_write_operations(transcript):
        written = write_checkpoint(transcript)
        print(f"checkpoint: {written}", file=sys.stderr)
    # If no write ops: exit 0 silently (read-only session, no checkpoint needed)


if __name__ == "__main__":
    main()
