'use server'

import { cookies } from 'next/headers'
import { redirect } from 'next/navigation'
import { z } from 'zod'

// Schema will be generated by Plan 05-03, hardcode for now
const LoginRequestSchema = z.object({
  username: z.string().min(1).max(100),
  password: z.string().min(1).max(100),
})

const TokenResponseSchema = z.object({
  access_token: z.string(),
  refresh_token: z.string(),
  token_type: z.string().default('Bearer'),
  expires_in: z.number().default(1800),
})

export async function loginAction(prevState: { error?: string } | null, formData: FormData) {
  const username = formData.get('username') as string
  const password = formData.get('password') as string

  const validated = LoginRequestSchema.safeParse({ username, password })
  if (!validated.success) {
    return { error: 'Invalid input' }
  }

  const response = await fetch(`${process.env.API_URL || 'http://api:8000'}/api/auth/login`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(validated.data),
  })

  if (!response.ok) {
    return { error: 'Invalid credentials' }
  }

  const parsed = TokenResponseSchema.safeParse(await response.json())
  if (!parsed.success) {
    return { error: 'Invalid server response' }
  }

  const cookieStore = await cookies()  // CRITICAL: await in Next.js 16 (Pitfall 5)
  cookieStore.set('access_token', parsed.data.access_token, {
    httpOnly: true,
    secure: process.env.NODE_ENV === 'production',
    sameSite: 'lax',
    maxAge: parsed.data.expires_in,
    path: '/',
  })
  cookieStore.set('refresh_token', parsed.data.refresh_token, {
    httpOnly: true,
    secure: process.env.NODE_ENV === 'production',
    sameSite: 'lax',
    maxAge: 86400,  // 24h
    path: '/',
  })

  redirect('/')
}
