// Generated by tonic-build from events.proto
pub mod mastermind {
    pub mod events {
        pub mod v1 {
            include!(concat!(env!("OUT_DIR"), "/mastermind.events.v1.rs"));
        }
    }
}
